pages:
  image: mhart/alpine-node:8.11.1
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk update && apk add --no-cache openssh )'
    - 'which curl || ( apk update && apk add --no-cache curl )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - yarn install
    - yarn build:prod
    - scp -r public softbutterfly@54.183.211.90:/home/softbutterfly/sites/flisol.softbutterfly.io/public.new
    - ssh softbutterfly@54.183.211.90 -C "rm -r /home/softbutterfly/sites/flisol.softbutterfly.io/public && mv /home/softbutterfly/sites/flisol.softbutterfly.io/public.new /home/softbutterfly/sites/flisol.softbutterfly.io/public"
    - curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" -H "X-Auth-Email:$CLOUDFLARE_EMAIL" -H "X-Auth-Key:$CLOUDFLARE_API_KEY" -H "Content-Type:application/json" --data '{"purge_everything":true}'
    - yarn build:gitlab
  artifacts:
    paths:
    - public
  only:
  - master
